app:
    name: MyClass
    version: 1.0.0-alpha0
    env: development

http:
    port: 8080
    origins:
        - http://localhost:8080
        - https://localhost:8080

postgres:
    port: 5432
    host: mc-postgres
    ssl: false

redis:
    port: 6379
    host: mc-redis
    ssl: false

auth:    
    jwt:
        access_ttl: 2h
        refresh_ttl: 168h
    hasher:
        salt_len: 16
        key_len: 79
        time: 3
        memory: 65536
        threads: 4